#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

../../../build_templates/mkmf -p restart_file_tool -t ../../../build_templatesf/mkmf.template   \
 -a "../../.." path_names_restart_file_tool

exit $status

