#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

     ../../../../../build_templates/mkmf -p exo_coldens.exe \
 -t  ../../../../../build_templates/mkmf.template \
 -a "../../../../.." path_names_exo_coldens

exit $status

