#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

     ../../../mkmf/mkmf -p preprocess \
 -t  ../../../mkmf/mkmf.template \
 -a "../../.." path_names_preprocess

exit $status

