#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

       ../../../mkmf/mkmf -p airnow_no2_ascii_to_obs \
-t     ../../../mkmf/mkmf.template \
-x -a "../../.." path_names_airnow_no2_ascii_to_obs

exit $status

